### ISSUE TITLE
Could not find function arrange

### ISSUE THREAD

**Issue by JohnCheetah** [hrbrmstr/streamgraph#16]
FYI:

    > streamgraph(dat, key = "key", value = "value", date = "date")
    Error in function_list[[k]](value) : could not find function "arrange"

so I loaded `plyr` and it fixed it

    library(plyr)

**Comment by hrbrmstr** [comment]
Please make sure you're using the latest version. The package imports `dplyr` so this should not be an issue.

**Comment by JohnCheetah** [comment]
Indeed. Sorry about that and thanks for the package!
