### ISSUE TITLE
CRAN?

### ISSUE THREAD

**Issue by zachcp** [hrbrmstr/streamgraph#17]
Hi  @hrbrmstr ,

This is an excellent, well written package that is one of the better examples of how to use D3 in HTMLWidgets.  I tried making a d3-htmlwidget at some point and got bogged down on a few things that you've figured out nicely - interactivity, select boxes, etc). In any event, I just nominated this for inclusion on [HTMLWidgets.org](https://github.com/ramnathv/htmlwidgets/issues/181) but was told that the package needs to be on CRAN. Just wanted to voice support for a release on CRAN and inclusion in HTML widgets.

zach cp

**Comment by nicholasjhorton** [comment]
Is there a reason why the package isn't on CRAN?  I too find it to be excellent and well-written.
