### ISSUE TITLE
Plot not appearing in RStudio

### ISSUE THREAD

**Issue by pssguy** [hrbrmstr/streamgraph#2]
First stab with 0.3.  and I'm getting a problem trying to use some babynames data
With your example

         str(dat)
        Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	791 obs. of  3 variables:
         $ year : Date, format: "1893-01-01" "1893-01-01" ...
         $ genre: Factor w/ 7 levels "Action","Animation",..: 1 2 3 4 5 6 7 1 2 3 ...
         $ n    : int  0 0 0 0 0 0 1 0 0 0 ...

    streamgraph(dat, "genre", "n", "year", interactive=TRUE)

No problemo

My data is very similar (I even named the columns the same) 

           str(namesDat)
            Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	1135 obs. of  3 variables:
             $ year : Date, format: "1880-01-01" "1880-01-01" ...
             $ genre: Factor w/ 9 levels "Charles","George",..: 5 9 4 1 2 3 8 7 5 9 ...
             $ n    : int  9655 9532 5927 5348 5126 404 103 22 8769 8524 ...
        

             streamgraph(namesDat, "genre", "n", "year", interactive=TRUE)

No error in console but blank  RStudio viewer and browser

Probably overlooking something obvious

**Comment by hrbrmstr** [comment]
prbly not. this pkg was rushed for an internal project. i'll poke at it
over the weekend.

**Comment by hrbrmstr** [comment]
Take a look at the latest Rmd example - http://rpubs.com/hrbrmstr/streamgraph_03 - and give the push I just did a go. I think it'll take care of all the cases, but we'll see.

**Comment by pssguy** [comment]
Looks good so far. Tx a lot
