### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by bctclc** [hrbrmstr/streamgraph#24]
Hi,

I couldn't install this package, and the problem is as followng:

Downloading GitHub repo hrbrmstr/streamgraph@master
from URL https://api.github.com/repos/hrbrmstr/streamgraph/zipball/master
Installing streamgraph
"D:/PROGRA~1/R-33~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD  \
  INSTALL  \
  "C:/Users/dell/AppData/Local/Temp/RtmpOITlnh/devtools217072476372/hrbrmstr-streamgraph-16aee37"  \
  --library="D:/Program File/R-3.3.1/library" --install-tests 

* installing *source* package 'streamgraph' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'zoo'
ERROR: lazy loading failed for package 'streamgraph'
* removing 'D:/Program File/R-3.3.1/library/streamgraph'
Error: Command failed (1)

I'd really appreciate if anyone can help me with it. Thanks a lot!

**Comment by hrbrmstr** [comment]
install the `zoo` package before installing this. I'm not sure why devtools install didn't auto-install the dependencies tho.

**Comment by bctclc** [comment]
@hrbrmstr Thank you so much!
