### ISSUE TITLE
Warning if supplied date is of class POSIXct

### ISSUE THREAD

**Issue by jemus42** [hrbrmstr/streamgraph#3]
> In if (class(data$date) %in% c("numeric", "character", "integer")) { :
  the condition has length > 1 and only the first element will be used

Since the plotting works fine with a date variable of class `POSIXct`, I think there shouldn't be a warning in this case.

**Comment by hrbrmstr** [comment]
Thx for giving the pkg a go and finding a bug! Give the push I just did a go (0.4.1). It should get rid of said error message.

**Comment by jemus42** [comment]
Thanks for the quick update, works as I expected now!
