### ISSUE TITLE
FR: Manually specifiy colors provided to sg_colors

### ISSUE THREAD

**Issue by jemus42** [hrbrmstr/streamgraph#5]
Consider the example data:

<pre>
ggplot2::movies %>%
  select(year, Action, Animation, Comedy, Drama, Documentary, Romance, Short) %>%
  tidyr::gather(genre, value, -year) %>%
  group_by(year, genre) %>%
  tally(wt=value) %>% head

  year       genre n
1 1893      Action 0
2 1893   Animation 0
3 1893      Comedy 0
4 1893       Drama 0
5 1893 Documentary 0
6 1893     Romance 0
</pre>

I would like to manually specifiy the colour for each value of `genre` instead of relying on a predefined palette.
A named vector would suffice, such as:

`c(Action = "black", Animation = "grey", Comedy = "blue", …)`

This would allow greater customizability of the output, and also be more intuitive for people like me, who are used to `ggplot2` and it's scale specifications.

**Comment by hrbrmstr** [comment]
definitely doable. I was thinking of a few `sg_color_` functions (e.g. `sg_color_brewer`, `sg_color_tableau`, `sg_color_manual`) and also renaming them to `sg_fill_`). thx.

**Comment by jemus42** [comment]
Sounds nice, looking forward to it \o/

**Comment by hrbrmstr** [comment]
the 0.5 push I just made might fill the gap for explicit categorical assignment of manual colors. per the documentation on `sg_fill_manual`, the streamgraph javascript code sorts the categorical values before mapping to the color palette, so the assignment is deterministic, just not explicit.

**Comment by abresler** [comment]
Take a look at ggthemes bob they have a bunch of great color palette I'm
sure you could borrow same with Wes Anderson

-- 
Alex Bresler

ASBC LLLC
asbcllc.com
917-455-0239

abresler@asbcllc.com
@abresler

**Comment by hrbrmstr** [comment]
that's where I got Tableau from :-)

**Comment by hrbrmstr** [comment]
Closing issue for basic feature creation. Will look to added named support in a future release.
